title: StarLight
description: "StarLight aims to lightweight deep neural networks and mainly includes three modules: network compression, neural architecture search, and visualization. The network compression module transforms a pre-trained network into a lightweight structure by utilizing pruning and quantization techniques. The neural architecture search module designs efficient structures by utilizing differentiable architecture search methods. All of the aforementioned processes can be displayed in the visualization window, and we also provide visualizations of network intermediate features."
theme: just-the-docs

url: https://ICT-ANS.github.io/StarLight.github.io

